2018.8.1

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -1,24 +1,18 @@
 #!/sbin/sh -x
 # Magisk Manager for Recovery Mode (mm) Installer
-# VR25 @ xda-developers
+# (c) 2017-2018, VR25 @ xda-developers
+# License: GPL v3+
 
-# Detect whether in boot mode
-ps | grep zygote | grep -v grep >/dev/null && BOOTMODE=true || BOOTMODE=false
-$BOOTMODE || ps -A 2>/dev/null | grep zygote | grep -v grep >/dev/null && BOOTMODE=true
-$BOOTMODE || id | grep -q 'uid=0' || BOOTMODE=true
+# detect whether in bootmode
+ps | grep zygote | grep -v grep >/dev/null && bootMode=true || bootMode=false
+$bootMode || ps -A 2>/dev/null | grep zygote | grep -v grep >/dev/null && bootMode=true
+$bootMode || id | grep -q 'uid=0' || bootMode=true
 
-# Add Magisk busybox to PATH
-$BOOTMODE && export PATH="/sbin/.core/busybox:/dev/magisk/bin:$PATH"
-
-# Default permissions
+# default perms
 umask 022
 
-##########################################################################################
-# Functions
-##########################################################################################
-
 ui_print() {
-  $BOOTMODE && echo -e "$1" || echo -e "ui_print $1\nui_print" >> /proc/self/fd/$OUTFD
+  $bootMode && echo -e "$1" || echo -e "ui_print $1\nui_print" >> /proc/self/fd/$OUTFD
 }
 
 grep_prop() {
@@ -32,24 +26,24 @@ grep_prop() {
 is_mounted() { mountpoint -q "$1"; }
 
 mount_image() {
-  ui_print "- Mounting $1 to $2"
-  [ -d "$2" ] || mkdir -p "$2"
-  if (! is_mounted $2); then
-    LOOPDEVICE=
-    for LOOP in 0 1 2 3 4 5 6 7; do
-      if (! is_mounted $2); then
-        LOOPDEVICE=/dev/block/loop$LOOP
-        [ -f "$LOOPDEVICE" ] || mknod $LOOPDEVICE b 7 $LOOP 2>/dev/null
-        losetup $LOOPDEVICE $1
-        if [ "$?" -eq "0" ]; then
-          mount -t ext4 -o loop $LOOPDEVICE $2
-          is_mounted $2 || /system/bin/toolbox mount -t ext4 -o loop $LOOPDEVICE $2
-          is_mounted $2 || /system/bin/toybox mount -t ext4 -o loop $LOOPDEVICE $2
-        fi
-        is_mounted $2 && break
-      fi
-    done
-  fi
+	ui_print "- Mounting $1 to $2"
+	[ -d "$2" ] || mkdir -p "$2"
+	if (! is_mounted $2); then
+		loopDevice=
+		for LOOP in 0 1 2 3 4 5 6 7; do
+			if (! is_mounted $2); then
+				loopDevice=/dev/block/loop$LOOP
+				[ -f "$loopDevice" ] || mknod $loopDevice b 7 $LOOP 2>/dev/null
+				losetup $loopDevice $1
+				if [ "$?" -eq "0" ]; then
+					mount -t ext4 -o loop $loopDevice $2
+					is_mounted $2 || /system/bin/toolbox mount -t ext4 -o loop $loopDevice $2
+					is_mounted $2 || /system/bin/toybox mount -t ext4 -o loop $loopDevice $2
+				fi
+				is_mounted $2 && break
+			fi
+		done
+	fi
 }
 
 set_perm() {
@@ -65,12 +59,6 @@ set_perm_recursive() {
   find "$1" -type f -o -type l 2>/dev/null | while read file; do
 	set_perm "$file" $2 $3 $5 $6
   done
-}
-
-mktouch() {
-  mkdir -p ${1%/*} 2>/dev/null
-  [ -z "$2" ] && touch "$1" || echo "$2" > "$1"
-  chmod 644 $1
 }
 
 request_size_check() {
@@ -92,9 +80,36 @@ image_size_check() {
   curSizeM=$((curSizeM * 4 / 1024))
 }
 
-##########################################################################################
-# Flashable update-binary preparation
-##########################################################################################
+mod_info() {
+  grep_prop "$1" $INSTALLER/module.prop
+}
+
+print_modname() {
+  ui_print " "
+  ui_print "$(mod_info name) ($(mod_info id)) $(mod_info version)"
+  ui_print "$(mod_info author)"
+  ui_print "Powered by Magisk (@topjohnwu)"
+  ui_print " "
+}
+
+set_permissions() {
+  # Only some special files require specific permissions
+  # The default permissions should be good enough for most cases
+
+  # Here are some examples for the set_perm functions:
+
+  # set_perm_recursive  <dirname>                <owner> <group> <dirpermission> <filepermission> <contexts> (default: u:object_r:system_file:s0)
+  # set_perm_recursive  $modPath/system/lib       0       0       0755            0644
+
+  # set_perm  <filename>                         <owner> <group> <permission> <contexts> (default: u:object_r:system_file:s0)
+  # set_perm  $modPath/system/bin/app_process32   0       2000    0755         u:object_r:zygote_exec:s0
+  # set_perm  $modPath/system/bin/dex2oat         0       2000    0755         u:object_r:dex2oat_exec:s0
+  # set_perm  $modPath/system/lib/libart.so       0       0       0644
+
+  # The following is default permissions, DO NOT remove
+  set_perm_recursive  $tmpModPath  0  0  0755  0644
+  set_perm /data/media/mm 0  0  0755
+}
 
 OUTFD=$2
 ZIP="$3"
@@ -115,13 +130,11 @@ if [ "$?" -eq "0" ]; then
   done
 fi
 
-# This path should work in any cases
-TMPDIR=/dev/tmp
-
-INSTALLER=$TMPDIR/install
-MOUNTPATH=$TMPDIR/magisk_img
-$BOOTMODE && IMGNAME=magisk_merge.img || IMGNAME=magisk.img
-[ -d /data/adb/magisk ] && IMG=/data/adb/$IMGNAME || IMG=/data/$IMGNAME
+tmpDir=/dev/tmp
+INSTALLER=$tmpDir/install
+mountPath=$tmpDir/magisk_img
+$bootMode && imgName=magisk_merge.img || imgName=magisk.img
+[ -d /data/adb/magisk ] && IMG=/data/adb/$imgName || IMG=/data/$imgName
 
 if [ ! -d /data/adb/magisk ] && [ ! -d /data/magisk ]; then
 	ui_print " "
@@ -130,148 +143,38 @@ if [ ! -d /data/adb/magisk ] && [ ! -d /data/magisk ]; then
 	exit 1
 fi
 
-# Initial cleanup
-rm -rf $TMPDIR 2>/dev/null
+# initial cleanup
+rm -rf $tmpDir 2>/dev/null
 mkdir -p $INSTALLER 2>/dev/null
 
 unzip -o "$ZIP" 'common/*' module.prop -d $INSTALLER >&2
 
-MODID="`grep_prop id $INSTALLER/module.prop`"
-TMP_MODPATH=$MOUNTPATH/$MODID
-MODPATH=$TMP_MODPATH
+modID="`grep_prop id $INSTALLER/module.prop`"
+tmpModPath=$mountPath/$modID
+modPath=$tmpModPath
 
-# Find MODPATH
-if $BOOTMODE; then
-  for MountPoint in /sbin/.core/img /magisk; do
-    if [ -d "$MountPoint/.core" ] || [ -d "$MountPoint/lost+found" ]; then
-      MountPoint=$MountPoint
-      MODPATH=$MountPoint/$MODID
-      mkdir -p $MODPATH 2>/dev/null
+# find modPath
+if $bootMode; then
+  for mountPoint in /sbin/.core/img /magisk; do
+    if [ -d "$mountPoint/.core" ] || [ -d "$mountPoint/lost+found" ]; then
+      mountPoint=$mountPoint
+      modPath=$mountPoint/$modID
+      mkdir -p $modPath 2>/dev/null
       break
     fi
   done
-
-	if [ ! -d "$MODPATH" ]; then
-		echo -e "(!) Magisk mount point not found"
-		exit 1
-	fi
-
-  if ! is_mounted $MountPoint; then
-    ui_print "(!) Magisk is not activated!... abort"
-    exit 1
-  fi
+  [[ -d $modPath ]] || { echo -e "\n(!) Magisk mount point not found\n"; exit 1; }
+  is_mounted $mountPoint || { echo -e "\n(!) Magisk is not activated!... abort\n"; exit 1; }
 fi
-
-##########################################################################################
-# Configs
-##########################################################################################
-
-# Set to true if you need to enable Magic Mount
-# Most mods would like it to be enabled
-AUTOMOUNT=false
-
-# Set to true if you need to load system.prop
-PROPFILE=false
-
-# Set to true if you need post-fs-data script
-POSTFSDATA=false
-
-# Set to true if you need late_start service script
-LATESTARTSERVICE=false
-
-ModVersion="`grep_prop version $INSTALLER/module.prop`"
-print_modname() {
-  ui_print "*************************************************"
-  ui_print "Magisk Manager for Recovery Mode (mm) $ModVersion"
-  ui_print "              VR25 @ xda-developers              "
-  ui_print "*************************************************"
-}
-
-# List all directories you want to directly replace in the system
-# Check the documentations for more info about how Magic Mount works, and why you need this
-
-# This is an example
-REPLACE="
-/system/app/Youtube
-/system/priv-app/SystemUI
-/system/priv-app/Settings
-/system/framework
-"
-
-# Construct your own list here, it will override the example above
-# !DO NOT! remove this if you don't need to replace anything, leave it empty as it is now
-REPLACE="
-"
-
-set_permissions() {
-  # Only some special files require specific permissions
-  # The default permissions should be good enough for most cases
-
-  # Here are some examples for the set_perm functions:
-
-  # set_perm_recursive  <dirname>                <owner> <group> <dirpermission> <filepermission> <contexts> (default: u:object_r:system_file:s0)
-  # set_perm_recursive  $MODPATH/system/lib       0       0       0755            0644
-
-  # set_perm  <filename>                         <owner> <group> <permission> <contexts> (default: u:object_r:system_file:s0)
-  # set_perm  $MODPATH/system/bin/app_process32   0       2000    0755         u:object_r:zygote_exec:s0
-  # set_perm  $MODPATH/system/bin/dex2oat         0       2000    0755         u:object_r:dex2oat_exec:s0
-  # set_perm  $MODPATH/system/lib/libart.so       0       0       0644
-
-  # The following is default permissions, DO NOT remove
-  set_perm_recursive  $TMP_MODPATH  0  0  0755  0644
-  set_perm	/data/media/mm	0	0	0755
-}
-
-##########################################################################################
-# Main
-##########################################################################################
 
 # Print mod name
 print_modname
 
-# Please leave this message in your flashable zip for credits :)
-ui_print "******************************"
-ui_print "Powered by Magisk (@topjohnwu)"
-ui_print "******************************"
-
-$BOOTMODE || ui_print "- Mounting partitions"
-# mount -o ro /system 2>/dev/null
-# mount -o ro /vendor 2>/dev/null
+$bootMode || ui_print "- Mounting partitions"
+mount -o ro /system 2>/dev/null
+mount -o ro /vendor 2>/dev/null
 mount /data 2>/dev/null
-# mount /cache 2>/dev/null
-
-# if [ ! -f '/system/build.prop' ]; then
-#   ui_print "(!) Failed: /system could not be mounted!"
-#   exit 1
-# fi
-
-# API=`grep_prop ro.build.version.sdk`
-# ABI=`grep_prop ro.product.cpu.abi | cut -c-3`
-# ABI2=`grep_prop ro.product.cpu.abi2 | cut -c-3`
-# ABILONG=`grep_prop ro.product.cpu.abi`
-
-# ARCH=arm
-# IS64BIT=false
-# if [ "$ABI" = "x86" ]; then ARCH=x86; fi;
-# if [ "$ABI2" = "x86" ]; then ARCH=x86; fi;
-# if [ "$ABILONG" = "arm64-v8a" ]; then ARCH=arm64; IS64BIT=true; fi;
-# if [ "$ABILONG" = "x86_64" ]; then ARCH=x64; IS64BIT=true; fi;
-
-# You can get the Android API version from $API, the CPU architecture from $ARCH
-# Useful if you are creating Android version / platform dependent mods
-
-if ! is_mounted /data; then
-  IMG=/cache/$IMGNAME
-  ui_print " "
-  ui_print "***********************************"
-  ui_print "*      !! Data unavailable !!     *"
-  ui_print "* Magisk detection is impossible  *"
-  ui_print "* Installation will still proceed *"
-  ui_print "*  But please make sure you have  *"
-  ui_print "*        Magisk installed!!       *"
-  ui_print "***********************************"
-  ui_print " "
-fi
+mount /cache 2>/dev/null
 
 request_zip_size_check "$ZIP"
 
@@ -289,70 +192,49 @@ else
   make_ext4fs -l ${SIZE}M $IMG >&2
 fi
 
-mount_image $IMG $MOUNTPATH
-if ! is_mounted $MOUNTPATH; then
+mount_image $IMG $mountPath
+if ! is_mounted $mountPath; then
+  ui_print " "
   ui_print "(!) $IMG mount failed... abort"
+  ui_print " "
   exit 1
 fi
 
 ##########################################################################################
-# Module space
+# module-specific code
 ##########################################################################################
 
-# Create mod paths
-rm -rf $TMP_MODPATH 2>/dev/null
-mkdir -p $TMP_MODPATH
-
-# Extract files
-ui_print "- Extracting files"
-unzip -o "$ZIP" mm -d /data/media >&2
-unzip -o "$ZIP" README.md -d $TMP_MODPATH >&2
+# create module paths
+rm -rf $tmpModPath 2>/dev/null
+mkdir -p $tmpModPath
+  
+# extract module files
+ui_print "- Extracting module files"
+unzip -o "$ZIP" -d $INSTALLER >&2
+cd $INSTALLER
+mv mm /data/media/
+mv README.md $tmpModPath/
 
 ##########################################################################################
 
-# Handle replace folders
-for TARGET in $REPLACE; do
-  mktouch $TMP_MODPATH$TARGET/.replace
-done
+# module info
+cp $INSTALLER/module.prop $tmpModPath/
 
-# Auto Mount
-if $AUTOMOUNT; then
-  mktouch $TMP_MODPATH/auto_mount
-fi
-
-# prop files
-if $PROPFILE; then
-  cp -af $INSTALLER/common/system.prop $TMP_MODPATH/system.prop
-fi
-
-# Module info
-cp -af $INSTALLER/module.prop $TMP_MODPATH/module.prop
-if $BOOTMODE; then
-  # Update info for Magisk Manager
-  mktouch $MODPATH/update
-  cp -af $INSTALLER/module.prop $MODPATH/module.prop
-fi
-
-# post-fs-data mode scripts
-if $POSTFSDATA; then
-  cp -af $INSTALLER/common/post-fs-data.sh $TMP_MODPATH/post-fs-data.sh
-fi
-
-# service mode scripts
-if $LATESTARTSERVICE; then
-  cp -af $INSTALLER/common/service.sh $TMP_MODPATH/service.sh
+# update info for Magisk Manager
+if $bootMode; then
+  touch $modPath/update
+  cp $INSTALLER/module.prop $modPath/
 fi
 
 ui_print "- Setting permissions"
 set_permissions
 
-$BOOTMODE || ui_print "- Unmounting partitions"
+$bootMode || ui_print "- Unmounting partitions"
+umount $mountPath
+losetup -d $loopDevice
+rmdir $mountPath
 
-umount $MOUNTPATH
-losetup -d $LOOPDEVICE
-rmdir $MOUNTPATH
-
-# Shrink the image if possible
+# shrink the image if possible
 image_size_check $IMG
 NEWDATASIZE=$((curUsedM / 32 * 32 + 32))
 if [ "$curSizeM" -gt "$NEWDATASIZE" ]; then
@@ -360,15 +242,19 @@ if [ "$curSizeM" -gt "$NEWDATASIZE" ]; then
   resize2fs $IMG ${NEWDATASIZE}M >&2
 fi
 
-# if ! $BOOTMODE; then
-#   umount /system
-#   umount /vendor 2>/dev/null
-# fi
+if ! $bootMode; then
+  umount /system
+  umount /vendor 2>/dev/null
+fi
 
-ui_print "- Done"
+ui_print "- End"
 ui_print " "
 
-if $BOOTMODE; then
+##########################################################################################
+# module-specific code
+##########################################################################################
+
+if $bootMode; then
 	ui_print "(i) Usage: run /data/media/mm on recovery terminal and follow the wizard"
 else
 	ln -s /data/media/mm /sbin
@@ -376,6 +262,9 @@ else
 	ui_print "- Next time, no need to reinstall -- run /data/media/mm"
 fi
 
-ui_print "- mm survives a standard TWRP factory reset"
+ui_print "- mm survives the standard TWRP factory reset"
 ui_print " "
+
+##########################################################################################
+
 exit 0
